# Generated by Django 5.2.13 on 2026-04-21 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('name', models.CharField(max_length=100, verbose_name='Tarla Adı')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Konum')),
                ('area_decar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alan (Dekar)')),
                ('soil_type', models.CharField(choices=[('killi', 'Killi'), ('kumlu', 'Kumlu'), ('tinli', 'Tınlı'), ('killi_tinli', 'Killi-Tınlı'), ('kumlu_tinli', 'Kumlu-Tınlı'), ('limolu', 'Limolu')], default='tinli', max_length=50, verbose_name='Toprak Tipi')),
                ('status', models.CharField(choices=[('empty', 'Boş'), ('planted', 'Ekili')], default='empty', max_length=20, verbose_name='Durum')),
                ('current_crop', models.CharField(blank=True, max_length=50, verbose_name='Mevcut Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Tarla',
                'verbose_name_plural': 'Tarlalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
