# Generated by Django 6.0.4 on 2026-04-29 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['user', 'status'], name='idx_field_user_status'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['user', '-created_at'], name='idx_field_user_created'),
        ),
    ]
