# Generated by Django 6.0.5 on 2026-05-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_idx_field_user_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('log_type', models.CharField(choices=[('irrigation', 'Sulama'), ('fertilization', 'Gübreleme')], default='irrigation', max_length=20, verbose_name='İşlem Tipi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Miktar (Litre veya kg)')),
                ('details', models.TextField(blank=True, verbose_name='Detaylar/Notlar')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_logs', to='fields.field', verbose_name='Tarla')),
            ],
            options={
                'verbose_name': 'Sulama/Gübreleme Kaydı',
                'verbose_name_plural': 'Sulama/Gübreleme Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', 'log_type', '-created_at'], name='idx_irrigation_field_type')],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nem (%)')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sıcaklık (°C)')),
                ('soil_moisture', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Toprak Nemi (%)')),
                ('plant_water_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Bitki Su Tüketimi (mm/gün)')),
                ('soil_ph', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Toprak pH')),
                ('light_intensity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Işık Yoğunluğu (Lux)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='fields.field', verbose_name='Tarla')),
            ],
            options={
                'verbose_name': 'Sensör Verisi',
                'verbose_name_plural': 'Sensör Verileri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', '-created_at'], name='idx_sensor_field_created')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('sensor_type', models.CharField(max_length=30, verbose_name='Sensör Tipi')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Değer')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Ham Veri')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Geçerli mi?')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='fields.field', verbose_name='Tarla')),
            ],
            options={
                'verbose_name': 'Sensör Okuması',
                'verbose_name_plural': 'Sensör Okumaları',
                'db_table': 'sensör_okumalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', 'sensor_type', '-created_at'], name='idx_sensorreading_field_type')],
            },
        ),
    ]
