# Generated by Django 5.2.14 on 2026-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Son Giriş IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Çiftçi'), ('admin', 'Yönetici'), ('agronomist', 'Agronomist')], db_index=True, default='farmer', max_length=20, verbose_name='Rol'),
        ),
    ]
