# Generated by Django 5.2.13 on 2026-04-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50, unique=True, verbose_name='Ürün (EN)')),
                ('crop_name_tr', models.CharField(max_length=50, verbose_name='Ürün (TR)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (TL/kg)')),
                ('avg_yield_per_hectare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ort. Verim (kg/ha)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Ürün Fiyatı',
                'verbose_name_plural': 'Ürün Fiyatları',
                'ordering': ['crop_name_tr'],
            },
        ),
        migrations.CreateModel(
            name='CareRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('recommendation_type', models.CharField(choices=[('irrigation', 'Sulama'), ('fertilization', 'Gübreleme'), ('pesticide', 'İlaçlama'), ('soil_amendment', 'Toprak Düzenleme'), ('temperature', 'Sıcaklık Uyarısı')], max_length=30, verbose_name='Tavsiye Tipi')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=10, verbose_name='Öncelik')),
                ('is_done', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_recommendations', to='fields.field', verbose_name='Tarla')),
            ],
            options={
                'verbose_name': 'Bakım Tavsiyesi',
                'verbose_name_plural': 'Bakım Tavsiyeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('nitrogen', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Azot (N)')),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fosfor (P)')),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Potasyum (K)')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sıcaklık (°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nem (%)')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='pH')),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Yağış (mm)')),
                ('source', models.CharField(choices=[('manual', 'Manuel Giriş'), ('simulation', 'Simülasyon')], default='manual', max_length=20, verbose_name='Kaynak')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='fields.field', verbose_name='Tarla')),
            ],
            options={
                'verbose_name': 'Toprak Analizi',
                'verbose_name_plural': 'Toprak Analizleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('crop_name', models.CharField(max_length=50, verbose_name='Ürün (EN)')),
                ('crop_name_tr', models.CharField(max_length=50, verbose_name='Ürün (TR)')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Güven Skoru (%)')),
                ('estimated_yield_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tahmini Verim (kg)')),
                ('estimated_revenue_tl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tahmini Kazanç (TL)')),
                ('rank', models.IntegerField(default=1, verbose_name='Sıralama')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.soilanalysis', verbose_name='Analiz')),
            ],
            options={
                'verbose_name': 'Ürün Önerisi',
                'verbose_name_plural': 'Ürün Önerileri',
                'ordering': ['rank'],
            },
        ),
    ]
