# Generated by Django 6.0.4 on 2026-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('fields', '0002_field_idx_field_user_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carerecommendation',
            index=models.Index(fields=['field', 'is_done', 'priority'], name='idx_care_field_done_prio'),
        ),
        migrations.AddIndex(
            model_name='croprecommendation',
            index=models.Index(fields=['analysis', 'rank'], name='idx_rec_analysis_rank'),
        ),
        migrations.AddIndex(
            model_name='soilanalysis',
            index=models.Index(fields=['field', '-created_at'], name='idx_soil_field_created'),
        ),
    ]
