# Generated by Django 6.0.5 on 2026-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_carerecommendation_idx_care_field_done_prio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=6)),
                ('val_accuracy', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('cv_mean_score', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('cv_std_score', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('training_time_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Model Logu',
                'verbose_name_plural': 'Model Logları',
                'db_table': 'model_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
